"""
Template mappings for PIT Count reports.
Extracted from calculator.py for better maintainability.
"""

from typing import List, Tuple, Dict

# All exact mappings from original template_mapping.py
MAPPING_WITH = [
    (("Total number of households", ""), 'Total_number_of_households'),
    (("Total number of persons (adults & children)", ""), 'Total_number_of_persons'),
    (("      Number of children (under age 18)", ""), 'Number_of_children'),
    (("      Number of young (age 18 to 24)", ""), 'Number_of_young_adults'),
    (("      Number of adults (age 25 to 34)", ""), 'Number_of_adults_25-34'),
    (("      Number of adults (age 35 to 44)", ""), 'Number_of_adults_35-44'),
    (("      Number of adults (age 45 to 54)", ""), 'Number_of_adults_45-54'),
    (("      Number of adults (age 55 to 64)", ""), 'Number_of_adults_55-64'),
    (("      Number of adults (age 65 or older)", ""), 'Number_of_adults_65+'),
    (("Gender (adults and children)", "Woman (Girl if child)"), 'Woman_Girl'),
    (("Gender (adults and children)", "Man (Boy if child)"), 'Man_Boy'),
    (("Gender (adults and children)", "Culturally Specific Identity"), 'Culturally_Specific_Identity'),
    (("Gender (adults and children)", "Transgender"), 'Transgender'),
    (("Gender (adults and children)", "Non-Binary"), 'Non_Binary'),
    (("Gender (adults and children)", "Questioning"), 'Questioning'),
    (("Gender (adults and children)", "Different Identity"), 'Different_Identity'),
    (("Gender (adults and children)", "More Than One Gender"), 'More_Than_One_Gender'),
    (("Gender (adults and children)", "      Includes Woman (Girl if child)"), 'Includes_Woman_Girl'),
    (("Gender (adults and children)", "      Includes Man (Boy if child)"), 'Includes_Man_Boy'),
    (("Gender (adults and children)", "      Includes Culturally Specific Identity"), 'Includes_Culturally_Specific_Identity'),
    (("Gender (adults and children)", "      Includes Transgender"), 'Includes_Transgender'),
    (("Gender (adults and children)", "      Includes Non-Binary"), 'Includes_Non_Binary'),
    (("Gender (adults and children)", "      Includes Questioning"), 'Includes_Questioning'),
    (("Gender (adults and children)", "      Includes Different Identity"),'Includes_Different_Identity'),
    (("Race and Ethnicity (adults and children)", "Indigenous (American Indian/Alaska Native/Indigenous)"), 'Indigenous'),
    (("Race and Ethnicity (adults and children)", "Indigenous (American Indian/Alaska Native/Indigenous) & Hispanic/Latina/e/o"), 'Indigenous_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Asian/Asian American"), 'Asian'),
    (("Race and Ethnicity (adults and children)", "Asian/Asian American & Hispanic/Latina/e/o"), 'Asian_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Black/African American/African"), 'Black'),
    (("Race and Ethnicity (adults and children)", "Black/African American/African & Hispanic/Latina/e/o"), 'Black_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Hispanic/Latina/e/o"), 'Hispanic'),
    (("Race and Ethnicity (adults and children)", "Middle Eastern/North African"), 'Middle_Eastern_North_African'),
    (("Race and Ethnicity (adults and children)", "Middle Eastern/North African & Hispanic/Latina/e/o"), 'Middle_Eastern_North_African_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Native Hawaiian/Pacific Islander"), 'Native_Hawaiian'),
    (("Race and Ethnicity (adults and children)", "Native Hawaiian/Pacific Islander & Hispanic/Latina/e/o"), 'Native_Hawaiian_Hispanic'),
    (("Race and Ethnicity (adults and children)", "White"), 'White'),
    (("Race and Ethnicity (adults and children)", "White & Hispanic/Latina/e/o"), 'White_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Multi-Racial & Hispanic/Latina/e/o"), 'Multi_Racial_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Multi-Racial (not Hispanic/Latina/e/o)"), 'Multi_Racial_Non_Hispanic'),
    (("Chronically Homeless", "Total number of households"), 'CH_Total_number_of_households'),
    (("Chronically Homeless", "Total number of persons"), 'CH_Total_number_of_persons')
]

MAPPING_WITHOUT = [
    (("Total number of households", ""), 'Total_number_of_households'),
    (("Total number of persons", ""), 'Total_number_of_persons'),
    (("      Number of young (age 18 to 24)", ""), 'Number_of_young_adults'),
    (("      Number of adults (age 25 to 34)", ""), 'Number_of_adults_25-34'),
    (("      Number of adults (age 35 to 44)", ""), 'Number_of_adults_35-44'),
    (("      Number of adults (age 45 to 54)", ""), 'Number_of_adults_45-54'),
    (("      Number of adults (age 55 to 64)", ""), 'Number_of_adults_55-64'),
    (("      Number of adults (age 65 or older)", ""), 'Number_of_adults_65+'),
    (("Gender", "Woman (Girl if child)"), 'Woman_Girl'),
    (("Gender", "Man (Boy if child)"), 'Man_Boy'),
    (("Gender", "Culturally Specific Identity"), 'Culturally_Specific_Identity'),
    (("Gender", "Transgender"), 'Transgender'),
    (("Gender", "Non-Binary"), 'Non_Binary'),
    (("Gender", "Questioning"), 'Questioning'),
    (("Gender", "Different Identity"), 'Different_Identity'),
    (("Gender", "More Than One Gender"), 'More_Than_One_Gender'),
    (("Gender", "      Includes Woman (Girl if child)"), 'Includes_Woman_Girl'),
    (("Gender", "      Includes Man (Boy if child)"), 'Includes_Man_Boy'),
    (("Gender", "      Includes Culturally Specific Identity"), 'Includes_Culturally_Specific_Identity'),
    (("Gender", "      Includes Transgender"), 'Includes_Transgender'),
    (("Gender", "      Includes Non-Binary"), 'Includes_Non_Binary'),
    (("Gender", "      Includes Questioning"), 'Includes_Questioning'),
    (("Gender", "      Includes Different Identity"),'Includes_Different_Identity'),
    (("Race and Ethnicity", "Indigenous (American Indian/Alaska Native/Indigenous)"), 'Indigenous'),
    (("Race and Ethnicity", "Indigenous (American Indian/Alaska Native/Indigenous) & Hispanic/Latina/e/o"), 'Indigenous_Hispanic'),
    (("Race and Ethnicity", "Asian/Asian American"), 'Asian'),
    (("Race and Ethnicity", "Asian/Asian American & Hispanic/Latina/e/o"), 'Asian_Hispanic'),
    (("Race and Ethnicity", "Black/African American/African"), 'Black'),
    (("Race and Ethnicity", "Black/African American/African & Hispanic/Latina/e/o"), 'Black_Hispanic'),
    (("Race and Ethnicity", "Hispanic/Latina/e/o"), 'Hispanic'),
    (("Race and Ethnicity", "Middle Eastern/North African"), 'Middle_Eastern_North_African'),
    (("Race and Ethnicity", "Middle Eastern/North African & Hispanic/Latina/e/o"), 'Middle_Eastern_North_African_Hispanic'),
    (("Race and Ethnicity", "Native Hawaiian/Pacific Islander"), 'Native_Hawaiian'),
    (("Race and Ethnicity", "Native Hawaiian/Pacific Islander & Hispanic/Latina/e/o"), 'Native_Hawaiian_Hispanic'),
    (("Race and Ethnicity", "White"), 'White'),
    (("Race and Ethnicity", "White & Hispanic/Latina/e/o"), 'White_Hispanic'),
    (("Race and Ethnicity", "Multi-Racial & Hispanic/Latina/e/o"), 'Multi_Racial_Hispanic'),
    (("Race and Ethnicity", "Multi-Racial (not Hispanic/Latina/e/o)"), 'Multi_Racial_Non_Hispanic'),
    (("Chronically Homeless", "Total number of persons"), 'CH_Total_number_of_persons')
]

MAPPING_WITHONLY = [
    (("Total number of households", ""), 'Total_number_of_households'),
    (("Number of children (persons under age 18)", ""), 'Total_number_of_persons'),
    (("Gender", "Woman (Girl if child)"), 'Woman_Girl'),
    (("Gender", "Man (Boy if child)"), 'Man_Boy'),
    (("Gender", "Culturally Specific Identity"), 'Culturally_Specific_Identity'),
    (("Gender", "Transgender"), 'Transgender'),
    (("Gender", "Non-Binary"), 'Non_Binary'),
    (("Gender", "Questioning"), 'Questioning'),
    (("Gender", "Different Identity"), 'Different_Identity'),
    (("Gender", "More Than One Gender"), 'More_Than_One_Gender'),
    (("Gender", "      Includes Woman (Girl if child)"), 'Includes_Woman_Girl'),
    (("Gender", "      Includes Man (Boy if child)"), 'Includes_Man_Boy'),
    (("Gender", "      Includes Culturally Specific Identity"), 'Includes_Culturally_Specific_Identity'),
    (("Gender", "      Includes Transgender"), 'Includes_Transgender'),
    (("Gender", "      Includes Non-Binary"), 'Includes_Non_Binary'),
    (("Gender", "      Includes Questioning"), 'Includes_Questioning'),
    (("Gender", "      Includes Different Identity"),'Includes_Different_Identity'),
    (("Race and Ethnicity", "Indigenous (American Indian/Alaska Native/Indigenous)"), 'Indigenous'),
    (("Race and Ethnicity", "Indigenous (American Indian/Alaska Native/Indigenous) & Hispanic/Latina/e/o"), 'Indigenous_Hispanic'),
    (("Race and Ethnicity", "Asian/Asian American"), 'Asian'),
    (("Race and Ethnicity", "Asian/Asian American & Hispanic/Latina/e/o"), 'Asian_Hispanic'),
    (("Race and Ethnicity", "Black/African American/African"), 'Black'),
    (("Race and Ethnicity", "Black/African American/African & Hispanic/Latina/e/o"), 'Black_Hispanic'),
    (("Race and Ethnicity", "Hispanic/Latina/e/o"), 'Hispanic'),
    (("Race and Ethnicity", "Middle Eastern/North African"), 'Middle_Eastern_North_African'),
    (("Race and Ethnicity", "Middle Eastern/North African & Hispanic/Latina/e/o"), 'Middle_Eastern_North_African_Hispanic'),
    (("Race and Ethnicity", "Native Hawaiian/Pacific Islander"), 'Native_Hawaiian'),
    (("Race and Ethnicity", "Native Hawaiian/Pacific Islander & Hispanic/Latina/e/o"), 'Native_Hawaiian_Hispanic'),
    (("Race and Ethnicity", "White"), 'White'),
    (("Race and Ethnicity", "White & Hispanic/Latina/e/o"), 'White_Hispanic'),
    (("Race and Ethnicity", "Multi-Racial & Hispanic/Latina/e/o"), 'Multi_Racial_Hispanic'),
    (("Race and Ethnicity", "Multi-Racial (not Hispanic/Latina/e/o)"), 'Multi_Racial_Non_Hispanic'),
    (("Chronically Homeless", "Total number of persons"), 'CH_Total_number_of_persons')
]

MAPPING_VET_WITH = [
    (("Total number of households", ""), 'Total_number_of_households'),
    (("Total number of persons", ""), 'Total_number_of_persons'),
    (("Total number of veterans", ""), 'Total number of veterans'),
    (("Gender (veterans only)", "Woman (Girl if child)"), 'Woman_Girl'),
    (("Gender (veterans only)", "Man (Boy if child)"), 'Man_Boy'),
    (("Gender (veterans only)", "Culturally Specific Identity"), 'Culturally_Specific_Identity'),
    (("Gender (veterans only)", "Transgender"), 'Transgender'),
    (("Gender (veterans only)", "Non-Binary"), 'Non_Binary'),
    (("Gender (veterans only)", "Questioning"), 'Questioning'),
    (("Gender (veterans only)", "Different Identity"), 'Different_Identity'),
    (("Gender (veterans only)", "More Than One Gender"), 'More_Than_One_Gender'),
    (("Gender (veterans only)", "      Includes Woman (Girl if child)"), 'Includes_Woman_Girl'),
    (("Gender (veterans only)", "      Includes Man (Boy if child)"), 'Includes_Man_Boy'),
    (("Gender (veterans only)", "      Includes Culturally Specific Identity"), 'Includes_Culturally_Specific_Identity'),
    (("Gender (veterans only)", "      Includes Transgender"), 'Includes_Transgender'),
    (("Gender (veterans only)", "      Includes Non-Binary"), 'Includes_Non_Binary'),
    (("Gender (veterans only)", "      Includes Questioning"), 'Includes_Questioning'),
    (("Gender (veterans only)", "      Includes Different Identity"),'Includes_Different_Identity'),
    (("Race and Ethnicity (veterans only)", "Indigenous (American Indian/Alaska Native/Indigenous)"), 'Indigenous'),
    (("Race and Ethnicity (veterans only)", "Indigenous (American Indian/Alaska Native/Indigenous) & Hispanic/Latina/e/o"), 'Indigenous_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Asian/Asian American"), 'Asian'),
    (("Race and Ethnicity (veterans only)", "Asian/Asian American & Hispanic/Latina/e/o"), 'Asian_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Black/African American/African"), 'Black'),
    (("Race and Ethnicity (veterans only)", "Black/African American/African & Hispanic/Latina/e/o"), 'Black_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Hispanic/Latina/e/o"), 'Hispanic'),
    (("Race and Ethnicity (veterans only)", "Middle Eastern/North African"), 'Middle_Eastern_North_African'),
    (("Race and Ethnicity (veterans only)", "Middle Eastern/North African & Hispanic/Latina/e/o"), 'Middle_Eastern_North_African_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Native Hawaiian/Pacific Islander"), 'Native_Hawaiian'),
    (("Race and Ethnicity (veterans only)", "Native Hawaiian/Pacific Islander & Hispanic/Latina/e/o"), 'Native_Hawaiian_Hispanic'),
    (("Race and Ethnicity (veterans only)", "White"), 'White'),
    (("Race and Ethnicity (veterans only)", "White & Hispanic/Latina/e/o"), 'White_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Multi-Racial & Hispanic/Latina/e/o"), 'Multi_Racial_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Multi-Racial (not Hispanic/Latina/e/o)"), 'Multi_Racial_Non_Hispanic'),
    (("Chronically Homeless", "Total number of households"), 'CH_Total_number_of_households'),
    (("Chronically Homeless", "Total number of persons"), 'CH_Total_number_of_persons')
]

MAPPING_VET_WITHOUT = [
    (("Total number of households", ""), 'Total_number_of_households'),
    (("Total number of persons", ""), 'Total_number_of_persons'),
    (("Total number of veterans", ""), 'Total number of veterans'),
    (("Gender (veterans only)", "Woman (Girl if child)"), 'Woman_Girl'),
    (("Gender (veterans only)", "Man (Boy if child)"), 'Man_Boy'),
    (("Gender (veterans only)", "Culturally Specific Identity"), 'Culturally_Specific_Identity'),
    (("Gender (veterans only)", "Transgender"), 'Transgender'),
    (("Gender (veterans only)", "Non-Binary"), 'Non_Binary'),
    (("Gender (veterans only)", "Questioning"), 'Questioning'),
    (("Gender (veterans only)", "Different Identity"), 'Different_Identity'),
    (("Gender (veterans only)", "More Than One Gender"), 'More_Than_One_Gender'),
    (("Gender (veterans only)", "      Includes Woman (Girl if child)"), 'Includes_Woman_Girl'),
    (("Gender (veterans only)", "      Includes Man (Boy if child)"), 'Includes_Man_Boy'),
    (("Gender (veterans only)", "      Includes Culturally Specific Identity"), 'Includes_Culturally_Specific_Identity'),
    (("Gender (veterans only)", "      Includes Transgender"), 'Includes_Transgender'),
    (("Gender (veterans only)", "      Includes Non-Binary"), 'Includes_Non_Binary'),
    (("Gender (veterans only)", "      Includes Questioning"), 'Includes_Questioning'),
    (("Gender (veterans only)", "      Includes Different Identity"),'Includes_Different_Identity'),
    (("Race and Ethnicity (veterans only)", "Indigenous (American Indian/Alaska Native/Indigenous)"), 'Indigenous'),
    (("Race and Ethnicity (veterans only)", "Indigenous (American Indian/Alaska Native/Indigenous) & Hispanic/Latina/e/o"), 'Indigenous_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Asian/Asian American"), 'Asian'),
    (("Race and Ethnicity (veterans only)", "Asian/Asian American & Hispanic/Latina/e/o"), 'Asian_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Black/African American/African"), 'Black'),
    (("Race and Ethnicity (veterans only)", "Black/African American/African & Hispanic/Latina/e/o"), 'Black_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Hispanic/Latina/e/o"), 'Hispanic'),
    (("Race and Ethnicity (veterans only)", "Middle Eastern/North African"), 'Middle_Eastern_North_African'),
    (("Race and Ethnicity (veterans only)", "Middle Eastern/North African & Hispanic/Latina/e/o"), 'Middle_Eastern_North_African_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Native Hawaiian/Pacific Islander"), 'Native_Hawaiian'),
    (("Race and Ethnicity (veterans only)", "Native Hawaiian/Pacific Islander & Hispanic/Latina/e/o"), 'Native_Hawaiian_Hispanic'),
    (("Race and Ethnicity (veterans only)", "White"), 'White'),
    (("Race and Ethnicity (veterans only)", "White & Hispanic/Latina/e/o"), 'White_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Multi-Racial & Hispanic/Latina/e/o"), 'Multi_Racial_Hispanic'),
    (("Race and Ethnicity (veterans only)", "Multi-Racial (not Hispanic/Latina/e/o)"), 'Multi_Racial_Non_Hispanic'),
    (("Chronically Homeless", "Total number of persons"), 'CH_Total_number_of_persons')
]

MAPPING_YOUTH_WITHOUT = [
    (("Total number of unaccompanied youth households", ""), 'Total_number_of_households'),
    (("Total number of unaccompanied youth", ""), 'Total_number_of_persons'),
    (("      Number of unaccompanied youth (under age 18)", ""), 'Number_of_children'),
    (("      Number of unaccompanied youth (age 18 to 24)", ""), 'Number_of_young_adults'),
    (("Gender (unaccompanied youth)", "Woman (Girl if child)"), 'Woman_Girl'),
    (("Gender (unaccompanied youth)", "Man (Boy if child)"), 'Man_Boy'),
    (("Gender (unaccompanied youth)", "Culturally Specific Identity"), 'Culturally_Specific_Identity'),
    (("Gender (unaccompanied youth)", "Transgender"), 'Transgender'),
    (("Gender (unaccompanied youth)", "Non-Binary"), 'Non_Binary'),
    (("Gender (unaccompanied youth)", "Questioning"), 'Questioning'),
    (("Gender (unaccompanied youth)", "Different Identity"), 'Different_Identity'),
    (("Gender (unaccompanied youth)", "More Than One Gender"), 'More_Than_One_Gender'),
    (("Gender (unaccompanied youth)", "      Includes Woman (Girl if child)"), 'Includes_Woman_Girl'),
    (("Gender (unaccompanied youth)", "      Includes Man (Boy if child)"), 'Includes_Man_Boy'),
    (("Gender (unaccompanied youth)", "      Includes Culturally Specific Identity"), 'Includes_Culturally_Specific_Identity'),
    (("Gender (unaccompanied youth)", "      Includes Transgender"), 'Includes_Transgender'),
    (("Gender (unaccompanied youth)", "      Includes Non-Binary"), 'Includes_Non_Binary'),
    (("Gender (unaccompanied youth)", "      Includes Questioning"), 'Includes_Questioning'),
    (("Gender (unaccompanied youth)", "      Includes Different Identity"),'Includes_Different_Identity'),
    (("Race and Ethnicity (unaccompanied youth)", "Indigenous (American Indian/Alaska Native/Indigenous)"), 'Indigenous'),
    (("Race and Ethnicity (unaccompanied youth)", "Indigenous (American Indian/Alaska Native/Indigenous) & Hispanic/Latina/e/o"), 'Indigenous_Hispanic'),
    (("Race and Ethnicity (unaccompanied youth)", "Asian/Asian American"), 'Asian'),
    (("Race and Ethnicity (unaccompanied youth)", "Asian/Asian American & Hispanic/Latina/e/o"), 'Asian_Hispanic'),
    (("Race and Ethnicity (unaccompanied youth)", "Black/African American/African"), 'Black'),
    (("Race and Ethnicity (unaccompanied youth)", "Black/African American/African & Hispanic/Latina/e/o"), 'Black_Hispanic'),
    (("Race and Ethnicity (unaccompanied youth)", "Hispanic/Latina/e/o"), 'Hispanic'),
    (("Race and Ethnicity (unaccompanied youth)", "Middle Eastern/North African"), 'Middle_Eastern_North_African'),
    (("Race and Ethnicity (unaccompanied youth)", "Middle Eastern/North African & Hispanic/Latina/e/o"), 'Middle_Eastern_North_African_Hispanic'),
    (("Race and Ethnicity (unaccompanied youth)", "Native Hawaiian/Pacific Islander"), 'Native_Hawaiian'),
    (("Race and Ethnicity (unaccompanied youth)", "Native Hawaiian/Pacific Islander & Hispanic/Latina/e/o"), 'Native_Hawaiian_Hispanic'),
    (("Race and Ethnicity (unaccompanied youth)", "White"), 'White'),
    (("Race and Ethnicity (unaccompanied youth)", "White & Hispanic/Latina/e/o"), 'White_Hispanic'),
    (("Race and Ethnicity (unaccompanied youth)", "Multi-Racial & Hispanic/Latina/e/o"), 'Multi_Racial_Hispanic'),
    (("Race and Ethnicity (unaccompanied youth)", "Multi-Racial (not Hispanic/Latina/e/o)"), 'Multi_Racial_Non_Hispanic'),
    (("Chronically Homeless", "Total number of persons"), 'CH_Total_number_of_persons')
]

MAPPING_YOUTH_WITH = [
    (("Total number of parenting youth household", ""), 'Total_number_of_households'),
    (("Total number of persons in parenting youth households", ""), 'Total_number_of_persons'),
    (("Total Parenting Youth (youth parents only)", ""), 'Total_Parenting_Youth'),
    (("Total Children in Parenting Youth Households", ""), 'Number_of_children'),
    (("   Number of parenting youth under age 18", ""), 'Number_of_parenting_youth_under_age_18'),
    (("      Children in households with parenting youth under age 18", ""), 'Children_with_parenting_youth_under_18'),
    (("   Number of parenting youth age 18 to 24", ""), 'Number_of_young_adults'),
    (("      Children in households with parenting youth age 18 to 24", ""), 'Children_with_parenting_youth_18_24'),
    (("Gender (youth parents only)", "Woman (Girl if child)"), 'Woman_Girl'),
    (("Gender (youth parents only)", "Man (Boy if child)"), 'Man_Boy'),
    (("Gender (youth parents only)", "Culturally Specific Identity"), 'Culturally_Specific_Identity'),
    (("Gender (youth parents only)", "Transgender"), 'Transgender'),
    (("Gender (youth parents only)", "Non-Binary"), 'Non_Binary'),
    (("Gender (youth parents only)", "Questioning"), 'Questioning'),
    (("Gender (youth parents only)", "Different Identity"), 'Different_Identity'),
    (("Gender (youth parents only)", "More Than One Gender"), 'More_Than_One_Gender'),
    (("Gender (youth parents only)", "      Includes Woman (Girl if child)"), 'Includes_Woman_Girl'),
    (("Gender (youth parents only)", "      Includes Man (Boy if child)"), 'Includes_Man_Boy'),
    (("Gender (youth parents only)", "      Includes Culturally Specific Identity"), 'Includes_Culturally_Specific_Identity'),
    (("Gender (youth parents only)", "      Includes Transgender"), 'Includes_Transgender'),
    (("Gender (youth parents only)", "      Includes Non-Binary"), 'Includes_Non_Binary'),
    (("Gender (youth parents only)", "      Includes Questioning"), 'Includes_Questioning'),
    (("Gender (youth parents only)", "      Includes Different Identity"),'Includes_Different_Identity'),
    (("Race and Ethnicity (youth parents only)", "Indigenous (American Indian/Alaska Native/Indigenous)"), 'Indigenous'),
    (("Race and Ethnicity (youth parents only)", "Indigenous (American Indian/Alaska Native/Indigenous) & Hispanic/Latina/e/o"), 'Indigenous_Hispanic'),
    (("Race and Ethnicity (youth parents only)", "Asian/Asian American"), 'Asian'),
    (("Race and Ethnicity (youth parents only)", "Asian/Asian American & Hispanic/Latina/e/o"), 'Asian_Hispanic'),
    (("Race and Ethnicity (youth parents only)", "Black/African American/African"), 'Black'),
    (("Race and Ethnicity (youth parents only)", "Black/African American/African & Hispanic/Latina/e/o"), 'Black_Hispanic'),
    (("Race and Ethnicity (youth parents only)", "Hispanic/Latina/e/o"), 'Hispanic'),
    (("Race and Ethnicity (youth parents only)", "Middle Eastern/North African"), 'Middle_Eastern_North_African'),
    (("Race and Ethnicity (youth parents only)", "Middle Eastern/North African & Hispanic/Latina/e/o"), 'Middle_Eastern_North_African_Hispanic'),
    (("Race and Ethnicity (youth parents only)", "Native Hawaiian/Pacific Islander"), 'Native_Hawaiian'),
    (("Race and Ethnicity (youth parents only)", "Native Hawaiian/Pacific Islander & Hispanic/Latina/e/o"), 'Native_Hawaiian_Hispanic'),
    (("Race and Ethnicity (youth parents only)", "White"), 'White'),
    (("Race and Ethnicity (youth parents only)", "White & Hispanic/Latina/e/o"), 'White_Hispanic'),
    (("Race and Ethnicity (youth parents only)", "Multi-Racial & Hispanic/Latina/e/o"), 'Multi_Racial_Hispanic'),
    (("Race and Ethnicity (youth parents only)", "Multi-Racial (not Hispanic/Latina/e/o)"), 'Multi_Racial_Non_Hispanic'),
    (("Chronically Homeless", "Total number of households"), 'CH_Total_number_of_households'),
    (("Chronically Homeless", "Total number of persons"), 'CH_Total_number_of_persons')
]

MAPPING_SUB = [
    (("Adults with a Serious Mental Illness", ""), 'Adults_with_a_Serious_Mental_Illness'),
    (("Adults with a Substance Use Disorder", ""), 'Adults_with_a_Substance_Use_Disorder'),
    (("Adults with HIV/AIDS", ""), 'Adults_with_a_HIV_AIDS'),
    (("Victims of Domestic Violence (fleeing)", ""), 'Victims_of_Domestic_Violence_(fleeing)')
]

MAPPING_SUMMARY = [
    (("Total number of households", ""), 'Total_number_of_households'),
    (("Total number of households", "Households with at Least One Adult and One Child"), 'Households_with_Child'),
    (("Total number of households", "      2 members"), 'Households_2_members'),
    (("Total number of households", "      3 members"), 'Households_3_members'),
    (("Total number of households", "      4 members"), 'Households_4_members'),
    (("Total number of households", "      5+ members"), 'Households_5+_members'),
    (("Total number of households", "Households without Children"), 'Households_without_Children'),
    (("Total number of households", "Households with Only Children"), 'Households_with_Only_Children'),

    (("Total number of persons", ""), 'Total_number_of_persons'),
    (("Total number of persons", "Number of children (under age 18)"), 'Number_of_children'),
    (("Total number of persons", "Number of young adults (age 18 to 24)"), 'Number_of_young_adults'),
    (("Total number of persons", "Adults (25-34)"), 'Number_of_adults_25-34'),
    (("Total number of persons", "Adults (35-44)"), 'Number_of_adults_35-44'),
    (("Total number of persons", "Adults (45-54)"), 'Number_of_adults_45-54'),
    (("Total number of persons", "Adults (55-64)"), 'Number_of_adults_55-64'),
    (("Total number of persons", "Adults (65+)"), 'Number_of_adults_65+'),
    (("Total number of persons", "Unreported Age"), 'Unreported_Age'),

    # Gender Categories
    (("Gender (adults and children)", "Woman (Girl if child)"), 'Woman_Girl'),
    (("Gender (adults and children)", "Man (Boy if child)"), 'Man_Boy'),
    (("Gender (adults and children)", "Culturally Specific Identity"), 'Culturally_Specific_Identity'),
    (("Gender (adults and children)", "Transgender"), 'Transgender'),
    (("Gender (adults and children)", "Non-Binary"), 'Non_Binary'),
    (("Gender (adults and children)", "Questioning"), 'Questioning'),
    (("Gender (adults and children)", "Different Identity"), 'Different_Identity'),
    (("Gender (adults and children)", "More Than One Gender"), 'More_Than_One_Gender'),
    (("Gender (adults and children)", "      Includes Woman (Girl if child)"), 'Includes_Woman_Girl'),
    (("Gender (adults and children)", "      Includes Man (Boy if child)"), 'Includes_Man_Boy'),
    (("Gender (adults and children)", "      Includes Culturally Specific Identity"), 'Includes_Culturally_Specific_Identity'),
    (("Gender (adults and children)", "      Includes Transgender"), 'Includes_Transgender'),
    (("Gender (adults and children)", "      Includes Non-Binary"), 'Includes_Non_Binary'),
    (("Gender (adults and children)", "      Includes Questioning"), 'Includes_Questioning'),
    (("Gender (adults and children)", "      Includes Different Identity"), 'Includes_Different_Identity'),

    # Race and Ethnicity Categories
    (("Race and Ethnicity (adults and children)", "Indigenous (American Indian/Alaska Native/Indigenous)"), 'Indigenous'),
    (("Race and Ethnicity (adults and children)", "Indigenous (American Indian/Alaska Native/Indigenous) & Hispanic/Latina/e/o"), 'Indigenous_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Asian/Asian American"), 'Asian'),
    (("Race and Ethnicity (adults and children)", "Asian/Asian American & Hispanic/Latina/e/o"), 'Asian_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Black/African American/African"), 'Black'),
    (("Race and Ethnicity (adults and children)", "Black/African American/African & Hispanic/Latina/e/o"), 'Black_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Hispanic/Latina/e/o"), 'Hispanic'),
    (("Race and Ethnicity (adults and children)", "Middle Eastern/North African"), 'Middle_Eastern_North_African'),
    (("Race and Ethnicity (adults and children)", "Middle Eastern/North African & Hispanic/Latina/e/o"), 'Middle_Eastern_North_African_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Native Hawaiian/Pacific Islander"), 'Native_Hawaiian'),
    (("Race and Ethnicity (adults and children)", "Native Hawaiian/Pacific Islander & Hispanic/Latina/e/o"), 'Native_Hawaiian_Hispanic'),
    (("Race and Ethnicity (adults and children)", "White"), 'White'),
    (("Race and Ethnicity (adults and children)", "White & Hispanic/Latina/e/o"), 'White_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Multi-Racial & Hispanic/Latina/e/o"), 'Multi_Racial_Hispanic'),
    (("Race and Ethnicity (adults and children)", "Multi-Racial (not Hispanic/Latina/e/o)"), 'Multi_Racial_Non_Hispanic'),

    # Subpopulations
    (("Subpopulations", "Chronically homeless HOUSEHOLDS"), 'CH_Total_number_of_households'),
    (("Subpopulations", "Chronically homeless persons"), 'CH_Total_number_of_persons'),
    (("Subpopulations", "Veterans"), 'Total number of veterans'),
    (("Subpopulations", "DV households"), 'Victims_of_Domestic_Violence_(Household)'),
    (("Subpopulations", "DV survivors"), 'Victims_of_Domestic_Violence_(fleeing)'),
    (("Subpopulations", "Unaccompanied youth households"), 'Total_Unaccompanied_Youth_hh'),
    (("Subpopulations", "Parenting youth households"), 'Total_Parenting_Youth_hh'),

    (("Chronic Health Conditions (Adults)", "Physical Disability"), 'Adults_with_a_Physical_Condition'),
    (("Chronic Health Conditions (Adults)", "Developmental Condition"), 'Adults_with_a_Developmental_Condition'),
    (("Chronic Health Conditions (Adults)", "Mental Health"), 'Adults_with_a_Serious_Mental_Illness'),
    (("Chronic Health Conditions (Adults)", "Chronic Substance Abuse"), 'Adults_with_a_Substance_Use_Disorder'),
    (("Chronic Health Conditions (Adults)", "HIV_AIDS"), 'Adults_with_a_HIV_AIDS'),
    (("Chronic Health Conditions (Adults)", "Other Chronic Health Conditions"), 'Adults_with_a_other_Condition'),

    (("Chronic Health Conditions (Children)", "Physical Disability"), 'childs_with_a_Physical_Condition'),
    (("Chronic Health Conditions (Children)", "Developmental Condition"), 'childs_with_a_Developmental_Condition'),
    (("Chronic Health Conditions (Children)", "Mental Health"), 'childs_with_a_Serious_Mental_Illness'),
    (("Chronic Health Conditions (Children)", "Chronic Substance Abuse"), 'childs_with_a_Substance_Use_Disorder'),
    (("Chronic Health Conditions (Children)", "HIV_AIDS"), 'childs_with_a_HIV_AIDS'),
    (("Chronic Health Conditions (Children)", "Other Chronic Health Conditions"), 'childs_with_a_other_Condition'),

    (("History of Homelessness", "First Time Homeless"), 'History_First_Time_Homeless'),
    (("History of Homelessness", "Length of Time Homeless(Less than one month)"), 'History_Less_than_One_Month'),
    (("History of Homelessness", "Length of Time Homeless(One to three months)"), 'History_One_to_Three_Months'),
    (("History of Homelessness", "Length of Time Homeless(Three months to one year)"), 'History_Three_Months_to_One_Year'),
    (("History of Homelessness", "Length of Time Homeless(One year or more)"), 'History_One_Year_or_More'),

    (("History of Homelessness (HHs)", "First Time Homeless"), 'History_HHs_First_Time_Homeless'),
    (("History of Homelessness (HHs)", "Length of Time Homeless(Less than one month)"), 'History_HHs_Less_than_One_Month'),
    (("History of Homelessness (HHs)", "Length of Time Homeless(One to three months)"), 'History_HHs_One_to_Three_Months'),
    (("History of Homelessness (HHs)", "Length of Time Homeless(Three months to one year)"), 'History_HHs_Three_Months_to_One_Year'),
    (("History of Homelessness (HHs)", "Length of Time Homeless(One year or more)"), 'History_HHs_One_Year_or_More')
]

def get_all_mappings() -> Dict[str, List[Tuple[Tuple[str, str], str]]]:
    """Return all mappings as a dictionary."""
    return {
        "mapping_with": MAPPING_WITH,
        "mapping_without": MAPPING_WITHOUT,
        "mapping_withonly": MAPPING_WITHONLY,
        "mapping_vet_with": MAPPING_VET_WITH,
        "mapping_vet_without": MAPPING_VET_WITHOUT,
        "mapping_youth_without": MAPPING_YOUTH_WITHOUT,
        "mapping_youth_with": MAPPING_YOUTH_WITH,
        "mapping_SUB": MAPPING_SUB,
        "mapping_Summary": MAPPING_SUMMARY
    }